spring.application.name=dbms_project

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dbms
spring.datasource.username=postgres
spring.datasource.password=Ndt2501><

#cau hinh sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=9gf8394hf34f3489fh3849hf9348hdsbhdsbhsdbvndjfcndsjfdjfjdsfj
jwt.expiration=86400000