spring.application.name=dbms_project

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dbms
spring.datasource.username=postgres
spring.datasource.password=vietanh2k5

#cau hinh sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=9gf8394hf34f3489fh3849hf9348hdsbhdsbhsdbvndjfcndsjfdjfjdsfj
jwt.expiration=86400000

# ==================================
# Cau hinh Buffer Ghi (Write Buffer)
# ==================================
# Kích ho?t tính n?ng gom lô (batch) c?a Hibernate và s? l??ng câu l?nh trong 1 lô
spring.jpa.properties.hibernate.jdbc.batch_size=50
# Yêu c?u Hibernate s?p x?p các câu l?nh gi?ng nhau l?i v?i nhau ?? t?i ?u t?c ?? g?i
spring.jpa.properties.hibernate.order_updates=true

# Cau hinh thoi gian xac buffer cho bo dem In-Memory tu code (ms)
app.buffer.progress.flush-delay-ms=10000